name: songlib
description: SongLib gives you access to your church songbook/hymns seamlessly that you don't have to worry about even being online once you have set up the app on your device.
publish_to: 'none'
version: 1.0.7

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  card_swiper: ^3.0.1
  context_menus: ^2.0.0+1
  cupertino_icons: ^1.0.6
  dartx: ^0.7.1
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_performance: ^0.10.0+3
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_lints: ^4.0.0
  flutter_localizations:
    sdk: flutter
  flutter_platform_alert: ^0.5.1
  fluttertoast: ^8.2.6
  formz: ^0.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http: ^1.2.1
  in_app_update: ^4.2.2
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  open_file: ^3.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.11.0
  pdf_viewer:
    path: packages/pdf_viewer
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  share_plus: ^9.0.0
  skeleton_loader: ^2.0.0+4
  sizer: ^2.0.15
  sqflite: ^2.3.3+1
  styled_widget: ^0.3.1
  textstyle_extensions: ^2.0.0-nullsafety
  timeago: ^3.6.1
  window_manager: ^0.3.9

dev_dependencies: 
  build_runner: ^2.4.6
  floor_generator: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.0
  msix: ^3.16.7
  mockito: ^5.0.15

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet-MS.ttf

msix_config:
  display_name: SongLib - Songs of Worship
  publisher_display_name: Jackson Siro
  identity_name: 49927JackonSiro.SongLib-SongsofWorship
  publisher: CN=FF945805-BB5A-4BF1-8668-776816B557C6
  msix_version: 1.0.7.65
  logo_path: assets\icons\app_icon.png
  architecture: x64
  capabilities: internetClient
  app_installer:
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: false
    force_update_from_any_version: false
  