name: songlib
description: SongLib gives you access to your church songbook/hymns seamlessly that you don't have to worry about even being online once you have set up the app on your device.
publish_to: 'none'
version: 0.1.96

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  camera: ^0.10.5+7
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dartx: ^0.7.1
  fl_chart: ^0.62.0
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+18
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  flutter_typeahead: ^4.8.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  http: ^0.13.6
  iconsax: ^0.0.8
  image_picker: ^0.8.4+4
  image_to_pdf_converter:
    git:
      url: https://github.com/talha828/Images_to_pdf
      path: packages/image_to_pdf_converter
  in_app_update: ^4.2.2
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  multi_image_picker_plus: ^0.0.4
  multi_image_picker_view: ^0.0.16
  open_file: ^3.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.10.4
  pdf_viewer:
    path: packages/pdf_viewer
  permission_handler: ^10.4.3
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  share_plus: ^7.2.1
  sizer: ^2.0.15
  sqflite: ^2.3.2
  styled_widget: ^0.3.1
  textstyle_extensions: ^2.0.0-nullsafety
  webview_flutter: ^4.4.4
  dropdown_search: ^5.0.6
  flutter_image_compress: ^2.2.0
  equatable: ^2.0.5
  formz: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0 
  mockito: ^5.0.15

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet-MS.ttf
